
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_db
spring.datasource.username=postgres
spring.datasource.password=ol123ol123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true